apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  annotations:
   checksum/config: {{ .Values.gitRev }}
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
